"""added validations

Revision ID: c2fb78601404
Revises: e5ed9da8a795
Create Date: 2023-11-19 22:44:54.755549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2fb78601404'
down_revision = 'e5ed9da8a795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.alter_column('arrival_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('departure_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('trains', schema=None) as batch_op:
        batch_op.alter_column('origin',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('destination',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trains', schema=None) as batch_op:
        batch_op.alter_column('destination',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('origin',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.alter_column('departure_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('arrival_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
